### ISSUE TITLE
DepthmapEngine Error

### ISSUE THREAD

**Issue by haktank5** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#188]
![3](https://user-images.githubusercontent.com/62407901/118032058-e33b7b00-b36f-11eb-8076-c01b44d69edc.JPG)

In some of my analysis studies, I get the error in the picture. Whatever I did, I could not solve this problem. Can you help me?

**Comment by AlexanderZuev1** [comment]
I have the same issue. Tried on qgis 3.10, 1.16 and 3.20.2
Used last version of depthmapXnet.
Process - using Graph analysis tool after clicking "calculate" button with any settings.

"Traceback (most recent call last):
  File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 690, in check_analysis_progress
    step, progress = self.analysis_engine.get_progress(self.axial_analysis_settings, self.datastore)
  File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 125, in get_progress
    return self.parse_progress(msg)
  File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 102, in parse_progress
    if self.analysis_nodes > 0:
AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'


Версия Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Версия: 3.10.0-A CoruÃ±a A CoruÃ±a, 6c816b4204"

P.S.
Версия - Version (translation from Russian)
If it will be necessary, i can send my geopackage file, where i store project and data

**Comment by AlexanderZuev1** [comment]
I have the same issue. Tried on qgis 3.10, 1.16 and 3.20.2
Used last version of depthmapXnet.
Process - using Graph analysis tool after clicking "calculate" button with any settings.

"Traceback (most recent call last):
File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 690, in check_analysis_progress
step, progress = self.analysis_engine.get_progress(self.axial_analysis_settings, self.datastore)
File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 125, in get_progress
return self.parse_progress(msg)
File "C:/Users/GK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 102, in parse_progress
if self.analysis_nodes > 0:
AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'

Версия Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Версия: 3.10.0-A CoruÃ±a A CoruÃ±a, 6c816b4204"

P.S.
Версия - Version (translation from Russian)
If it will be necessary, i can send my geopackage file, where i store project and data

**Comment by constance5690** [comment]
Hello, I'm having the same issue, has this been resolved?
