### ISSUE TITLE
Attribute error: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'

### ISSUE THREAD

**Issue by Intuos5** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#199]
On Windows 10, Qgis 3.16.9, DepthmapXnet 0.35 I get the following error:

2022-02-10T13:45:42     WARNING    Traceback (most recent call last):
              File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 690, in check_analysis_progress
              step, progress = self.analysis_engine.get_progress(self.axial_analysis_settings, self.datastore)
              File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 125, in get_progress
              return self.parse_progress(msg)
              File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 102, in parse_progress
              if self.analysis_nodes > 0:
             AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'

**Comment by imcake** [comment]
same issue.

**Comment by MKIM1008** [comment]
Same issue in Qgis 3.20.2

**Comment by jorgegil** [comment]
Can you please tell us know if it runs in other circumstances? For example does it work with axial analysis, or segment analysis but with unlinks, or using the sample data?

Thanks

**Comment by SojungNoh** [comment]
Same issue here. Sample data provided by the tutorial worked fine.

**Comment by jorgegil** [comment]
Can you provide a sample of the data that does not work? Thank you.

**Comment by SojungNoh** [comment]
Hello. 

Thank you for your quick reply. 
I'm trying to run 'segment analysis' with the following file in the link.
It is also contained in this link as well, which I've also wrote in the 'issue' page : https://drive.google.com/drive/folders/1EvjhHaJsjFNaWJoKwTQr5EaFOxE4PFX5
(The mail service is failing to send zip files because of the size, so please refer to this link.)

Thank you.
Best Regards, Sojung Noh.

-----Original Message-----
