### ISSUE TITLE
AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'

### ISSUE THREAD

**Issue by SojungNoh** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#203]
I'm currently having problem with :
_**AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'**_

**My Settings :**
On Windows 10, Qgis 3.28, DepthmapXnet 0.35 I get the following error, when running an analysis with these settings:
- Running analysis for map layer 'Segmentlines':
- analysis type - segment input
- distance - metric
- metric radius - n
- calculate choice
- calculate NACH and NAIN
- I don't have a layer set for unlinks.
(This setting is almost same as the issue #199, except 'distance')

**For your information, I attach the source file I'm aiming to analyse**
https://drive.google.com/drive/folders/1EvjhHaJsjFNaWJoKwTQr5EaFOxE4PFX5?usp=sharing

`2022-02-10T13:45:42 WARNING Traceback (most recent call last):
File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 690, in check_analysis_progress
step, progress = self.analysis_engine.get_progress(self.axial_analysis_settings, self.datastore)
File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 125, in get_progress
return self.parse_progress(msg)
File "C:\Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\DepthmapNetEngine.py", line 102, in parse_progress
if self.analysis_nodes > 0:
AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes'`

**Comment by RobinPetersson** [comment]
I'm having the same issue, please advice

**Comment by Kimseoungyeol** [comment]
안녕하세요. 혹시 해결하셨을까요? 저도 어려움이 있네요 ㅜㅜ

**Comment by SojungNoh** [comment]
아니요 ㅠㅠ 해결하지 못하고 그냥 뎁스맵으로 했네욥 ㅠㅠ


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 3. 25 오후 3:41:17
제목: Re: [SpaceGroupUCL/qgisSpaceSyntaxToolkit] AttributeError: 'DepthmapNetEngine' object has no attribute 'analysis_nodes' (Issue #203)

안녕하세요. 혹시 해결하셨을까요? 저도 어려움이 있네요 ㅜㅜ

**Comment by Kimseoungyeol** [comment]
아 ㅠㅠ 저도 뎁스맵으로 분석할게 있는데 파일크기가 커서 그런지 안돌아가네요 ㅜㅜ
혹시 축선도 작성에서 한번씩 꺼지던데 왜그런지 아시나요??

-----Original Message-----

**Comment by jorgegil** [comment]
@n-bristow Thanks for pointing this out. I have made a new release 0.3.10 available in github for now.

I would appreciate if people that flagged the issue (#199 , #188, #189, #203) would install this v0.3.10 in QGIS from the downloaded zip and test it. If it works, I will publish it in the QGIS plugins repository for automated updates.

Apologies for the slow response, since I am not actively involved in SST development any more. The contributions and fixes from the community are greatly appreciated!

**Comment by n-bristow** [comment]
@jorgegil Many thanks for this, I will try the zip and feedback. Thanks again.

**Comment by n-bristow** [comment]
Just an immediate bit of feedback on this - I'm getting an error when I try to install the zip on both windows and mac which I've copied below. I'll see if I can look into it a bit more, but just posting it here incase it is obvious. @jorgegil I'm mindful of your comment about not being actively involved in development!

Couldn't load plugin 'esstoolkit_0_3_10' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'esstoolkit' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/nickbristow/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/esstoolkit_0_3_10/__init__.py", line 25, in classFactory
    from .EssToolkit import EssToolkit
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nickbristow/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/esstoolkit_0_3_10/EssToolkit.py", line 50, in 
    from .ProjectManager import ProjectManager
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nickbristow/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/esstoolkit_0_3_10/ProjectManager.py", line 24, in 
    from esstoolkit.utilities import db_helpers as dbh, shapefile_helpers as shph
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'esstoolkit'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.22.14-Białowieża Białowieża, 4cde646cf9

**Comment by n-bristow** [comment]
I think this is because the folder inside the zip is called `esstoolkit_0_3_10` so it ends up installed as e.g.

`QGIS\QGIS3\profiles\default\python\plugins\esstoolkit_0_3_10` which QGIS doesn't seem able to work with.

Manually renaming that folder to `esstoolkit` lets it work.

**Comment by jorgegil** [comment]
Thanks for checking @n-bristow! Makes sense.
I'll update the plugin zip file for installation and wait a bit longer for feedback on actual use of the tool.

**Comment by jorgegil** [comment]
I've merged the latest fixes to the code (thank you @n-bristow!) and did a quick test. The "esstoolkit.zip" in the release is updated accordingly.

I will wait a few days for feedback from @n-bristow or others on this latest fix, then I'll upload to the QGIS plugins repository.
