### ISSUE TITLE
Failed to import the analysis results.

### ISSUE THREAD

**Issue by Munhui-Y** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#210]
2024-11-15T16:51:24     WARNING    warning:C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py:888: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
              mod = _builtin_import(name, globals, locals, fromlist, level)
             
             traceback: File "", line 1, in 
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 443, in startPlugin
              if not _startPlugin(packageName):
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\__init__.py", line 25, in classFactory
              from .EssToolkit import EssToolkit
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\EssToolkit.py", line 58, in 
              from esstoolkit.rcl_cleaner import road_network_cleaner_tool
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1058, in _handle_fromlist
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\rcl_cleaner\road_network_cleaner_tool.py", line 19, in 
              from future import standard_library
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1058, in _handle_fromlist
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\PROGRA~1\QGIS32~1.14\apps\Python39\lib\site-packages\future\standard_library\__init__.py", line 65, in 
              import imp
              File "C:\PROGRA~1/QGIS32~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\PROGRA~1\QGIS32~1.14\apps\Python39\lib\imp.py", line 31, in 
              warnings.warn("the imp module is deprecated in favour of importlib; "
             
2024-11-15T16:52:55     WARNING    warning:C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\engines\DepthmapNet\DepthmapNetEngine.py:65: ResourceWarning: unclosed 
              self.socket = DepthmapNetSocket()
             
             traceback: File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 568, in run_analysis
              if self.analysis_engine.ready():
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\engines\DepthmapNet\DepthmapNetEngine.py", line 54, in ready
              return self.connect_depthmap_net()
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\engines\DepthmapNet\DepthmapNetEngine.py", line 65, in connect_depthmap_net
              self.socket = DepthmapNetSocket()
             
2024-11-15T17:38:58     WARNING    warning:C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\AttributeSymbology.py:64: DeprecationWarning: QgsGraduatedSymbolRenderer.createRenderer() is deprecated
              renderer = QgsGraduatedSymbolRenderer.createRenderer(layer, attribute, intervals, mode, symbol, ramp)
             
             traceback: File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerDialog.py", line 145, in __selectCurrentLayer
              self.layerChanged.emit()
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerTool.py", line 242, in updateLayerAttributes
              self.dlg.setCurrentAttribute(current_attribute)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerDialog.py", line 177, in setCurrentAttribute
              self.attributesList.setCurrentRow(idx)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerTool.py", line 353, in updateSymbology
              renderer = self.attributeSymbology.updateRenderer(self.current_layer, attribute, settings)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\AttributeSymbology.py", line 64, in updateRenderer
              renderer = QgsGraduatedSymbolRenderer.createRenderer(layer, attribute, intervals, mode, symbol, ramp)
             
2024-11-15T17:38:58     WARNING    warning:C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\AttributeSymbology.py:65: DeprecationWarning: QgsGraduatedSymbolRenderer.setMode() is deprecated
              renderer.setMode(mode)
             
             traceback: File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerDialog.py", line 145, in __selectCurrentLayer
              self.layerChanged.emit()
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerTool.py", line 242, in updateLayerAttributes
              self.dlg.setCurrentAttribute(current_attribute)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerDialog.py", line 177, in setCurrentAttribute
              self.attributesList.setCurrentRow(idx)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\ExplorerTool.py", line 353, in updateSymbology
              renderer = self.attributeSymbology.updateRenderer(self.current_layer, attribute, settings)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\explorer\AttributeSymbology.py", line 65, in updateRenderer
              renderer.setMode(mode)

2024-11-15T16:52:23     WARNING    Traceback (most recent call last):
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\analysis\AnalysisTool.py", line 576, in run_analysis
              raise AnalysisEngine.AnalysisEngineError("Analysis settings invalid")
             esstoolkit.analysis.engines.AnalysisEngine.AnalysisEngine.AnalysisEngineError: Analysis settings invalid
            
Running analysis for map layer '1114_segv2':
   analysis type - segment
   stubs removal - 40
   distance - angular
   metric radius - 0
   calculate choice
   calculate NACH and NAIN

Start: 15/11/2024 17:40:25
...
Finish: 15/11/2024 17:40:26
Post-processing: Failed!
Total running time: 0:00:01.002508

2024-11-15T17:40:26     WARNING    Info : Failed to import the analysis results.
My setup :
Qgis 3.28.14
python 9.5.7
depthmapX0.35
windows10 x64

I can't  import the analysis results. How to fix?
Analytics worked fine a month ago, now it doesn't. What's the problem?

**Comment by jorgegil** [comment]
This problem has been reported in previous issues #129 #167 , and in some there is also offered a solution in issue #208 .

We have not solved it because we have not found a consistent pattern that causes the issue. It's not hardware, operating system, QGIS version, data format dependent. My suspicion is that it could be something related to the data that goes in, but I haven't been able to confirm.

Hopefully the discussions above can help you...
